### ISSUE TITLE
ResinBot[Public]: Integration could be used to trigger resin.io App builds from code in Github

### ISSUE THREAD

**Issue by hedss** [balena-io-modules/resin-procbots#21]
Currently resin.io only consumes from our own git repos for each Application.

A public `resin.io Github` ProcBot Integration could be made available on the Github Dashboard that users could attach to their own repos, so every time a push to Github occurs, the ProcBot picks it up and triggers the builder to run on it.

This would require hosting this public service, but would probably gain a lot of goodwill.

**Comment by CameronDiver** [comment]
Love it! The only issue I can foresee atm is how we get the auth keys to where they need to be. Other than that it seems like a fairly good to thing to be doing!

**Comment by CameronDiver** [comment]
I'm going to close this as it's likely to be implemented with balenaCI/balenaBuilder
